"""add image_file to pet

Revision ID: 258eed3cff83
Revises: eea1eb8b6c81
Create Date: 2024-06-05 23:15:01.179984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258eed3cff83'
down_revision = 'eea1eb8b6c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
