"""add created_at to pet

Revision ID: 54842f22c69b
Revises: 823e13702aa3
Create Date: 2024-06-08 00:31:53.497426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54842f22c69b'
down_revision = '823e13702aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
