"""Add ava

Revision ID: 5f7cd74950c6
Revises: 49fcb0499034
Create Date: 2024-06-06 04:38:46.243099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7cd74950c6'
down_revision = '49fcb0499034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'shelter', ['shelter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shelter_id')

    # ### end Alembic commands ###
