"""Initial migration.

Revision ID: a88c1a91660d
Revises: 4dcd1c9afb77
Create Date: 2024-05-29 21:50:22.924209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a88c1a91660d'
down_revision = '4dcd1c9afb77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'pet_id')
    )
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelter_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('pet_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'shelter', ['shelter_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('image_file')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_index('username')
        batch_op.drop_column('image_file')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('image_file', mysql.VARCHAR(length=20), nullable=False))
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pet_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.drop_column('shelter_id')

    op.drop_table('favorites')
    op.drop_table('shelter')
    # ### end Alembic commands ###
