""" to user

Revision ID: c04b7c57369b
Revises: a545fe5fa6da
Create Date: 2024-06-05 23:47:09.137780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c04b7c57369b'
down_revision = 'a545fe5fa6da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'avatar', ['avatar_id'], ['id'])
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('avatar_id')

    # ### end Alembic commands ###
