"""Add cascade delete to favorites

Revision ID: f67d1a090d79
Revises: c04b7c57369b
Create Date: 2024-06-06 03:31:00.625379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67d1a090d79'
down_revision = 'c04b7c57369b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'pet', ['pet_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_ibfk_1', 'pet', ['pet_id'], ['id'])

    # ### end Alembic commands ###
